Melogies-master/WebApplication2/Models/WELL.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WELL
    {
        public int OBJECTID { get; set; }
        [Display(Name = "Adı")]
        public string NAME { get; set; }

        [Display(Name = "Yerləşdiyi Ərazi")]
        public string LOCATION { get; set; }

        [Display(Name = "Tipi")]
        public string WELL_TYPE { get; set; }
        public string ASSIGMENT { get; set; }

        [Display(Name = "SİB-lər")]
        public string SIB { get; set; }

        [Display(Name = "İstismara verildiyi tarix")]
        public string EXPLONATION_DATE { get; set; }
        public Nullable<short> ACTIVITY { get; set; }

        [Display(Name = "Xidmət etdiyi sahə")]
        public string IRRIGATED_AREA { get; set; }

        [Display(Name = "Texniki vəziyyəti")]
        public string TECHNICAL_CONDITION { get; set; }

        [Display(Name = "Dərinliyi")]
        public string DEPTH { get; set; }

        [Display(Name = "Mülkiyyət növü")]
        public string PROPERTY_TYPE { get; set; }

        [Display(Name = "Mülkiyyətçi")]
        public string PROPERTY { get; set; }

        [Display(Name = "Bəndin Növü")]
        public string NUMBER_ { get; set; }
        public string PRODUCTIVITY { get; set; }
        public string SECURITY_TYPE { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public Nullable<int> Municipality_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> USER_ADMIN_ID { get; set; }
    }
}

Melogies-master/WebApplication2/Areas/Admin/Controllers/WELLsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Areas.Admin.Controllers
{
    public class WELLsController : Controller
    {
        private MelogisEntities db = new MelogisEntities();
        
        [AdminAuthenticationController]
        public ActionResult Index()
        {
            int logUser = (int)Session["UserAdmin"];
            return View(db.WELLs.Where(s => s.USER_ADMIN_ID == logUser).ToList());
        }


        [HttpPost]
        public ActionResult Index(List<WELL> wll)
        {
            foreach (var item in wll)
            {
                db.Entry(item).State = EntityState.Modified;
                db.Entry(item).Property(c => c.SHAPE).IsModified = false;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult WeLL()
        {
            return View(db.WELLs.ToList());
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Melogies-master/WebApplication2/Areas/Admin/Views/WELLs/Index.cshtml
@model IEnumerable<WebApplication2.Models.WELL>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div class="card mb-3">
    <div class="card-body" style="padding-bottom:0;">
        <div class="table-responsive">
            <table style="width:2000px" class="table table-bordered" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.NAME)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.LOCATION)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.WELL_TYPE)
                            <hr style="width:206px" />
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.ASSIGMENT)
                            <hr style="width:206px" />
                        </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.SIB)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.EXPLONATION_DATE)
                            <hr style="width:206px" />
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.ACTIVITY)
                            <hr style="width:206px" />
                        </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.IRRIGATED_AREA)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TECHNICAL_CONDITION)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DEPTH)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PROPERTY_TYPE)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PROPERTY)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.NUMBER_)
                            <hr style="width:206px" />
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.PRODUCTIVITY)
                            <hr style="width:206px" />
                        </th>*@
                        @*<th>
                            @Html.DisplayNameFor(model => model.SECURITY_TYPE)
                            <hr style="width:206px" />
                        </th>*@
                        @*<th>
                            @Html.DisplayNameFor(model => model.NOTE)
                            <hr style="width:206px" />
                        </th>*@
                        @*<th>
                            @Html.DisplayNameFor(model => model.Region_ID)
                            <hr style="width:206px" />
                        </th>*@
                        @*<th>
                            @Html.DisplayNameFor(model => model.Municipality_ID)
                            <hr style="width:206px" />
                        </th>*@
                        @*<th>
                            @Html.DisplayNameFor(model => model.USER_ADMIN_ID)
                            <hr style="width:206px" />
                        </th>*@
                    </tr>
                </thead>
            </table>
            <div style="width:2098px; height:70vh;overflow:auto;">
                <table class="table table-bordered" id="dataTable" cellspacing="0">
                    <tbody>
                        @using (Html.BeginForm("Index", "WELLs", FormMethod.Post))
                        {
                            int i = 0;
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td style="display:none">
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.OBJECTID" name="wll[@i].OBJECTID" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.NAME" name="wll[@i].NAME" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.LOCATION" name="wll[@i].LOCATION" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.WELL_TYPE" name="wll[@i].WELL_TYPE" />
                                            </div>
                                        </div>
                                    </td>
                                    <td style="display:none">
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.ASSIGMENT" name="wll[@i].ASSIGMENT" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.SIB" name="wll[@i].SIB" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.EXPLONATION_DATE" name="wll[@i].EXPLONATION_DATE" />
                                            </div>
                                        </div>
                                    </td>
                                    <td style="display:none">
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.ACTIVITY" name="wll[@i].ACTIVITY" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.IRRIGATED_AREA" name="wll[@i].IRRIGATED_AREA" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.TECHNICAL_CONDITION" name="wll[@i].TECHNICAL_CONDITION" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.DEPTH" name="wll[@i].DEPTH" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.PROPERTY_TYPE" name="wll[@i].PROPERTY_TYPE" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.PROPERTY" name="wll[@i].PROPERTY" />
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.NUMBER_" name="wll[@i].NUMBER_" />
                                            </div>
                                        </div>
                                    </td>
                                    <td style="display:none">
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.PRODUCTIVITY" name="wll[@i].PRODUCTIVITY" />
                                            </div>
                                        </div>
                                    </td>
                                    <td style="display:none">
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.SECURITY_TYPE" name="wll[@i].SECURITY_TYPE" />
                                            </div>
                                        </div>
                                    </td>
                                    <td style="display:none">
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.NOTE" name="wll[@i].NOTE" />
                                            </div>
                                        </div>
                                    </td>
                                    <td style="display:none">
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.Region_ID" name="wll[@i].Region_ID" />
                                            </div>
                                        </div>
                                    </td>
                                    <td style="display:none">
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.Municipality_ID" name="wll[@i].Municipality_ID" />
                                            </div>
                                        </div>
                                    </td>
                                    <td style="display:none">
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.USER_ADMIN_ID" name="wll[@i].USER_ADMIN_ID" />
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                i++;
                            }
                            <div class="text-right" style="padding:10px; width:100px; position:fixed; top:0px; right:85px; z-index:1;">
                                <button class="btn btn-primary">Yadda Saxla</button>
                            </div>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Melogies-master/WebApplication2/Areas/Admin/Views/WELLs/WeLL.cshtml
@model IEnumerable<WebApplication2.Models.WELL>
@{
    ViewBag.Title = "WeLL";
    Layout = "~/Views/Shared/NazirlikLayout.cshtml";
}

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Data Table Example
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.NAME)</th>
                        <th>@Html.DisplayNameFor(model => model.LOCATION)</th>
                        <th>@Html.DisplayNameFor(model => model.WELL_TYPE)</th>
                        <th>@Html.DisplayNameFor(model => model.SIB)</th>
                        <th>@Html.DisplayNameFor(model => model.EXPLONATION_DATE)</th>
                        <th>@Html.DisplayNameFor(model => model.IRRIGATED_AREA)</th>
                        <th>@Html.DisplayNameFor(model => model.TECHNICAL_CONDITION)</th>
                        <th>@Html.DisplayNameFor(model => model.DEPTH)</th>
                        <th>@Html.DisplayNameFor(model => model.PROPERTY_TYPE)</th>
                        <th>@Html.DisplayNameFor(model => model.PROPERTY)</th>
                        <th>@Html.DisplayNameFor(model => model.NUMBER_)</th>


                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.NAME)</th>
                        <th>@Html.DisplayNameFor(model => model.LOCATION)</th>
                        <th>@Html.DisplayNameFor(model => model.WELL_TYPE)</th>
                        <th>@Html.DisplayNameFor(model => model.SIB)</th>
                        <th>@Html.DisplayNameFor(model => model.EXPLONATION_DATE)</th>
                        <th>@Html.DisplayNameFor(model => model.IRRIGATED_AREA)</th>
                        <th>@Html.DisplayNameFor(model => model.TECHNICAL_CONDITION)</th>
                        <th>@Html.DisplayNameFor(model => model.DEPTH)</th>
                        <th>@Html.DisplayNameFor(model => model.PROPERTY_TYPE)</th>
                        <th>@Html.DisplayNameFor(model => model.PROPERTY)</th>
                        <th>@Html.DisplayNameFor(model => model.NUMBER_)</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.NAME</td>
                        <td>@item.LOCATION</td>
                        <td>@item.WELL_TYPE</td>
                        <td>@item.SIB</td>
                        <td>@item.EXPLONATION_DATE</td>
                        <td>@item.IRRIGATED_AREA</td>
                        <td>@item.TECHNICAL_CONDITION</td>
                        <td>@item.DEPTH</td>
                        <td>@item.PROPERTY_TYPE</td>
                        <td>@item.PROPERTY</td>
                        <td>@item.NUMBER_</td>

                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>