Melogies-master/WebApplication2/Models/ARTEZIAN_WELL.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ARTEZIAN_WELL
    {
        public int OBJECTID { get; set; }
        [Display(Name = "Yerləşdiyi yer")]
        public string LOCATED_AREA { get; set; }
        [Display(Name = "Reper nömrəsi")]
        public string REPER_NO { get; set; }
        [Display(Name = "Tipi")]
        public string WELL_TYPE { get; set; }
        [Display(Name = "Təyinatı")]
        public string ASSIGMENT { get; set; }
        public Nullable<decimal> PRODUCTIVITY { get; set; }
        [Display(Name = "Aid olduğu SİB")]
        public string SIB { get; set; }
        [Display(Name = "İstismara verildiyi tarix")]
        public string EXPLONATION_DATE { get; set; }
        public string ACTIVITY { get; set; }
        public Nullable<decimal> IRRIGATED_AREA { get; set; }
        [Display(Name = "Mülkiyyətçi")]
        public string PROPERTY { get; set; }
        [Display(Name = "Mülkiyyət növü")]
        public string PROPERTY_TYPE { get; set; }
        public Nullable<decimal> DEPTH { get; set; }
        public Nullable<decimal> NUMBER_ { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> WATER_CAPABILITY { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public Nullable<int> Municipality_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> USER_ADMIN_ID { get; set; }
    }
}

Melogies-master/WebApplication2/Areas/Admin/Controllers/ARTEZIAN_WELLController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Areas.Admin.Controllers
{
    public class ARTEZIAN_WELLController : Controller
    {
        private MelogisEntities db = new MelogisEntities();

        [AdminAuthenticationController]
        public ActionResult Index()
        {
            int logUser = (int)Session["UserAdmin"];
            return View(db.ARTEZIAN_WELL.Where(s => s.USER_ADMIN_ID == logUser).ToList());
        }

        [HttpPost]
        public ActionResult Index(List<ARTEZIAN_WELL> art)
        {
            foreach (var item in art)
            {
                db.Entry(item).State = EntityState.Modified;
                db.Entry(item).Property(c => c.SHAPE).IsModified = false;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult ArtizianWEll()
        {
            return View(db.ARTEZIAN_WELL.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Melogies-master/WebApplication2/Areas/Admin/Views/ARTEZIAN_WELL/ArtizianWEll.cshtml
@model IEnumerable<WebApplication2.Models.ARTEZIAN_WELL>
@{
    ViewBag.Title = "ArtizianWEll";
    Layout = "~/Views/Shared/NazirlikLayout.cshtml";
}

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Data Table Example
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.LOCATED_AREA)</th>
                        <th>@Html.DisplayNameFor(model => model.REPER_NO)</th>
                        <th>@Html.DisplayNameFor(model => model.WELL_TYPE)</th>
                        <th>@Html.DisplayNameFor(model => model.ASSIGMENT)</th>
                        <th>@Html.DisplayNameFor(model => model.SIB)</th>
                        <th>@Html.DisplayNameFor(model => model.EXPLONATION_DATE)</th>
                        <th>@Html.DisplayNameFor(model => model.PROPERTY)</th>
                        <th>@Html.DisplayNameFor(model => model.PROPERTY_TYPE)</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.LOCATED_AREA)</th>
                        <th>@Html.DisplayNameFor(model => model.REPER_NO)</th>
                        <th>@Html.DisplayNameFor(model => model.WELL_TYPE)</th>
                        <th>@Html.DisplayNameFor(model => model.ASSIGMENT)</th>
                        <th>@Html.DisplayNameFor(model => model.SIB)</th>
                        <th>@Html.DisplayNameFor(model => model.EXPLONATION_DATE)</th>
                        <th>@Html.DisplayNameFor(model => model.PROPERTY)</th>
                        <th>@Html.DisplayNameFor(model => model.PROPERTY_TYPE)</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.LOCATED_AREA</td>
                        <td>@item.REPER_NO</td>
                        <td>@item.WELL_TYPE</td>
                        <td>@item.ASSIGMENT</td>
                        <td>@item.SIB</td>
                        <td>@item.EXPLONATION_DATE</td>
                        <td>@item.PROPERTY</td>
                        <td>@item.PROPERTY_TYPE</td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

Melogies-master/WebApplication2/Areas/Admin/Views/ARTEZIAN_WELL/Index.cshtml
@model IEnumerable<WebApplication2.Models.ARTEZIAN_WELL>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div class="card mb-3">
    <div class="card-body" style="padding-bottom:0;">
        <div class="table-responsive">
            <table style="width:1860px" class="table table-bordered" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.LOCATED_AREA)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.REPER_NO)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.WELL_TYPE)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ASSIGMENT)
                            <hr style="width:206px" />
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.PRODUCTIVITY)
                            <hr style="width:206px" />
                        </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.SIB)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.EXPLONATION_DATE)
                            <hr style="width:206px" />
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.ACTIVITY)
                            <hr style="width:206px" />
                        </th>*@
                        @*<th>
                            @Html.DisplayNameFor(model => model.IRRIGATED_AREA)
                            <hr style="width:206px" />
                        </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.PROPERTY)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PROPERTY_TYPE)
                            <hr style="width:206px" />
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.DEPTH)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.NUMBER_)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.X)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Y)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.WATER_CAPABILITY)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Region_ID)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Municipality_ID)
                            <hr style="width:206px" />
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.USER_ADMIN_ID)
                            <hr style="width:206px" />
                        </th>*@
                    </tr>
                </thead>
            </table>
            <div style="width:1959px; height:70vh;overflow:auto;">
                <table class="table table-bordered" id="dataTable" cellspacing="0">
                    <tbody>
                        @using (Html.BeginForm("Index", "ARTEZIAN_WELL", FormMethod.Post))
                        {
                            int i = 0;
                            foreach (var item in Model)
                            {
                                 <tr>
                                     <td style="display:none">
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input value="@item.OBJECTID" name="art[@i].OBJECTID" />
                                            </div>
                                        </div>
                                    </td>
                                     <td>
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.LOCATED_AREA" name="art[@i].LOCATED_AREA" />
                                             </div>
                                         </div>
                                     </td>
                                     <td>
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.REPER_NO" name="art[@i].REPER_NO" />
                                             </div>
                                         </div>
                                     </td>
                                     <td>
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.WELL_TYPE" name="art[@i].WELL_TYPE" />
                                             </div>
                                         </div>
                                     </td>
                                     <td>
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.ASSIGMENT" name="art[@i].ASSIGMENT" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.PRODUCTIVITY" name="art[@i].PRODUCTIVITY" />
                                             </div>
                                         </div>
                                     </td>
                                     <td>
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.SIB" name="art[@i].SIB" />
                                             </div>
                                         </div>
                                     </td>
                                     <td>
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.EXPLONATION_DATE" name="art[@i].EXPLONATION_DATE" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.ACTIVITY" name="art[@i].ACTIVITY" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.IRRIGATED_AREA" name="art[@i].IRRIGATED_AREA" />
                                             </div>
                                         </div>
                                     </td>
                                     <td>
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.PROPERTY" name="art[@i].PROPERTY" />
                                             </div>
                                         </div>
                                     </td>
                                     <td>
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.PROPERTY_TYPE" name="art[@i].PROPERTY_TYPE" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.DEPTH" name="art[@i].DEPTH" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.NUMBER_" name="art[@i].NUMBER_" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.X" name="art[@i].X" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.Y" name="art[@i].Y" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.WATER_CAPABILITY" name="art[@i].WATER_CAPABILITY" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.Region_ID" name="art[@i].Region_ID" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.Municipality_ID" name="art[@i].Municipality_ID" />
                                             </div>
                                         </div>
                                     </td>
                                     <td style="display:none">
                                         <div class="form-group">
                                             <div class="col-md-10">
                                                 <input value="@item.USER_ADMIN_ID" name="art[@i].USER_ADMIN_ID" />
                                             </div>
                                         </div>
                                     </td>
                                </tr>
                                i++;
                            }
                            <div class="text-right" style="padding:10px; width:100px; position:fixed; top:0px; right:85px; z-index:1;">
                                <button class="btn btn-primary">Yadda Saxla</button>
                            </div>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>